# Laboratorium 4 — NumPy zaawansowane
**Autor:** [Miłosz Kapek]

In [1]:
import numpy as np

In [2]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99], # Produkt A
[49.99, 52.99, 47.99], # Produkt B
[14.99, 15.99, 13.99], # Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") # (4, 3)

Kształt macierzy: (4, 3)


# Broadcasting: macierz (4×3) * skalar

print(ceny * 1.05)

# Broadcasting: macierz (4×3) * wektor (3,)

In [3]:
rabaty = np.array([0.10, 0.05, 0.15])
print(ceny * (1 - rabaty))

[[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


# Broadcasting: macierz (4×3) * wektor kolumnowy (4×1)

In [4]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
print(ceny / (1 + marza))

[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


# Wyświetl najtańszy sklep dla każdego produktu.

In [10]:
temp1 = np.array(sklepy)
print(temp1[ceny.argmin(axis=1)])

['Online' 'Online' 'Online' 'Online']


# Reshape


In [11]:
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


# Stacking

In [ ]:
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])
# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")


Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


# Praktyczne (samodzielnie)

In [17]:
# Masz dane o sprzedaży 6 produktów jako wektor
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
# Wiesz, że to 6 produktów × 2 miesiące
# 1. Reshape na macierz 6×2
sprzedaz = sprzedaz_flat.reshape(6,2)
print(f'sprzedaz\n{sprzedaz}')
# 2. Oblicz średnią sprzedaż per produkt (axis=1)
srednia = sprzedaz.mean(axis=1)
print(f'srednia kazdego produktu:\n{srednia}')
# 3. Oblicz zmianę między miesiącem 1 a 2 (kolumna 1 - kolumna 0)
# Podpowiedź: macierz[:, 1] - macierz[:, 0]
temp2 = np.array(sprzedaz[:,1] - sprzedaz[:,0])
print(f'roznica dla kazdego produktu:\n{temp2}')

sprzedaz
[[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]
srednia kazdego produktu:
[150. 225. 215. 170. 240. 225.]
roznica dla kazdego produktu:
[100 150 -70 100 140 -70]


# Flatten i concatenate

In [24]:
# Masz macierz kwartałów z zadania 2a
# 1. Spłaszcz ją z powrotem do wektora (.flatten())
kwartaly_flat = kwartaly.flatten()
print(kwartaly_flat)
# 2. Dodaj dane z 13. miesiąca (wartość: 235) — np.concatenate()
# Podpowiedź: np.concatenate([wektor, np.array([235])])
temp3 = np.concatenate([kwartaly_flat,np.array([235])])
print(temp3)

[120 135  98 142 167 189 201 178 156 143 198 221]
[120 135  98 142 167 189 201 178 156 143 198 221 235]


# Analiza danych finansowych 

In [25]:
np.random.seed(6767)
# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])
# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

# Analiza wynagrodzeń


In [32]:
# 1. Oblicz średnią, medianę i odchylenie standardowe pensji
# Podpowiedź: pensje.mean(), np.median(pensje), pensje.std()
srednia = pensje.mean()
med = np.median(pensje)
odch = pensje.std()
print(f'średnia: {srednia} mediana: {med} odchylenie standardowe: {odch}')
# 2. Wyświetl imiona osób zarabiających powyżej średniej
# Uwaga: pracownicy to lista — zamień na np.array(pracownicy), żeby użyć maski
# Podpowiedź: nazwy = np.array(pracownicy), potem nazwy[pensje > pensje.mean()]
pracownicyarray = np.array(pracownicy)
temp4 = pracownicyarray[pensje > srednia]
print(temp4)
# 3. Wyświetl imiona osób zarabiających poniżej mediany
temp5 = pracownicyarray[pensje < med]
print(temp5)
# 4. Oblicz rozstęp (max - min) i rozstęp międzykwartylowy (IQR)
# Podpowiedź: IQR = np.percentile(pensje, 75) - np.percentile(pensje, 25)
rozstep = pensje.max() - pensje.min()
print(rozstep)

średnia: 6425.0 mediana: 6050.0 odchylenie standardowe: 1616.9029037020127
['Jan' 'Marek' 'Zofia']
['Anna' 'Ewa' 'Piotr' 'Tomek']
4900
