**Autor:** Miłosz Kapek

In [2]:
import numpy as np

In [ ]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [3]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [6]:
# 5. 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [18]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(40)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 5 3 2 2 4 3 2 5 4 5 5 4 5 5 5 5 3 2]


In [19]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


In [21]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy:                     0    1   2    3    4    5    6    7    8    9   10    11
# Miesiące:                   Sty  Lut  Mar Kwi  Maj  Cze  Lip  Sie  Wrz  Paź  Lis  Gru

In [22]:
# Zad1
print(miesiace_sprzedaz[0])

120


In [23]:
# Zad2
print(miesiace_sprzedaz[-1])

221


In [25]:
# Zad3
print(miesiace_sprzedaz[0:3])

[120 135  98]


In [26]:
# Zad4
print(miesiace_sprzedaz[-3:])

[143 198 221]


In [27]:
# Zad5
print(miesiace_sprzedaz[::2])

[120  98 167 201 156 198]


In [29]:
# Zad6
print(miesiace_sprzedaz[::-1])

[221 198 143 156 178 201 189 167 142  98 135 120]


In [30]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [53]:
print(dane[0,0])

120


In [49]:
print(dane[2])

[234 267 289]


In [48]:
print(dane[:,0])

[120  89 234  56]


In [51]:
print(dane[1:3,1:3])

[[102  95]
 [267 289]]


**Operacje Wektorowe**

**Cel**:
Użyj operacji NumPy do rozwiązania problemów biznesowych. 

In [3]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

# Średnia cena, najdroższy produkt, najtańszy produkt

In [65]:
print(f'Średnia cena {ceny.mean()}')
print(f'Najdroższy produkt: {nazwy[ceny.argmax()]}')
print(f'Najtańszy produkt: {nazwy[ceny.argmin()]}')


Średnia cena 1171.0
Najdroższy produkt: Laptop
Najtańszy produkt: Ładowarka


# Oblicz wartość każdego produktu (cena × ilość) i łączną wartość magazynu

In [69]:
wartość_magazynu = np.zeros(10)
wartość_magazynu = ceny * ilosci_magazyn
print(np.sum(wartość_magazynu))

549465


# Stworz array z cenami po rabacie 15% (promocja świąteczna)

In [71]:
ceny_po_rabat = ceny * 0.85
print(f'Ceny po rabacie: {ceny_po_rabat}')

Ceny po rabacie: [2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]


# Stworz array z cenami po uwzględnieniu VAT 23%

In [72]:
ceny_po_vat = ceny * 1.23
print(f'Ceny po uwzgędnieniu vat {ceny_po_vat}')

Ceny po uwzgędnieniu vat [4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]


# Ile produktów kosztuje powyżej 1000 zł?

In [73]:
temp1 = np.array(ceny>1000).sum()
print(temp1)

4


# Produkty z oceną >= 4.5 — nazwy i ceny

In [80]:
for i in range(0,10):
    if oceny_klientow[i] >= 4.5:
        print(f'Nazwa: {nazwy[i]} cena: {ceny[i]}')

Nazwa: Laptop cena: 3499
Nazwa: Smartfon cena: 2499
Nazwa: Słuchawki cena: 349
Nazwa: Monitor cena: 1499


# Produkty poniżej 200 zł — nazwy i ilości w magazynie

In [4]:
nazwy_arr = np.array(nazwy)
temp1 = np.array(ceny < 200)
print(f'Produkty tańsze niż 200zł {nazwy_arr[temp1]}')


Produkty tańsze niż 200zł ['Ładowarka' 'Mysz']


# Produkty z niskim stanem magazynowym (< 30 szt.) — nazwy

In [5]:
temp2 = ilosci_magazyn < 30
print(f'Produkty z niskim stanem magazynowym {nazwy_arr[temp2]}')

Produkty z niskim stanem magazynowym ['Laptop' 'Monitor']


# Łączna wartość tych produktów

In [8]:
wartosc = ceny * ilosci_magazyn
wartoscNiski = wartosc[temp2].sum()
print(wartoscNiski)

86962


# Ile % magazynu stanowią

In [10]:
wartoscProcentowa = wartoscNiski / wartosc.sum() * 100
print(f'{round(wartoscProcentowa,2)} %') 

15.83 %


In [11]:
import time

# Przygotowanie danych

In [12]:
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

# Test 1: Pomnóż przez 2

In [13]:
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 61.0 ms
NumPy: 3.5 ms
NumPy jest 17× szybszy!


# Test 2: Suma

In [14]:
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista: 5.1 ms
NumPy: 1.2 ms
NumPy jest 4× szybszy!


# Test 3: Filtrowanie (elementy > 500000)

In [15]:
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 30.8 ms
NumPy: 2.5 ms
NumPy jest 13× szybszy!


## Wnioski z benchmarku
- NumPy jest **17×** szybszy w mnożeniu
- NumPy jest **4×** szybszy w sumowaniu
- NumPy jest **13×** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list